POST http://Localhost:3001/api/notes 
Content-Type: application/json

{
   "content":"Aprender ingles",
   "important":true
}

###

POST http://Localhost:3001/api/notes 
Content-Type: application/json

{
   "content":"",
   "important":true
}

## 

PUT http://Localhost:3001/api/notes/1
Content-Type: application/json

{
   "body":"test",
}